name: salesapp
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#version: 2.0.0+1   #this is for ios
version: 1.0.0+15    #this is for android

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  badges: ^2.0.1
  intl: ^0.17.0
  fluttertoast: ^8.0.9
  sizer: ^2.0.15
  pie_chart: ^5.3.0
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.0.20
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  universal_html: ^2.0.8
  carousel_slider: ^4.1.1
  date_time_picker: ^2.1.0
  syncfusion_flutter_datepicker: ^20.2.45
  loading_indicator: ^3.1.0
  path_provider: ^2.0.5
  flutter_pdfview: ^1.2.0
  permission_handler: ^10.0.0
  share: ^2.0.4
  #  image_picker: ^1.0.4
  payu_checkoutpro_flutter: ^1.1.4
  crypto: ^3.0.3
  #  progress_dialog: ^1.2.4
  flutter_easyloading: ^3.0.5
  #  device_info_plus: ^7.0.0
  shared_preferences: ^2.2.0
  pdf: ^3.8.4
  printing: ^5.9.3
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    #    - assets/images/salesmanager.png
    - assets/images/



flutter_icons:
  image_path: "assets/icon/emis.png"
  android: "launcher_icon"
  ios: true

